module.exports={
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    CATEGORY_COLLECTION:'category',
    PRODUCT_COLLECTION:'product',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    ADDRESS_COLLECTION:'address',
    WISHLIST_COLLECTION:'wishlist',
    COUPON_COLLECTION:'coupon',
    BANNER_COLLECTION:'banner'
}